require('plugins')
require('keybindiings')
require('options')
require('nvim-tree-config')
require('lualine-config')
require('bufferline-config')
require('telescope-config')
require('treesitter-config')
require('dashboard-config')
require('whichkey-config')
require('toggleterm-config')
require('competitest-config')
require('luasnip-config')
require('null-ls-config')
require('cmp-config')
require('mason-config')
require('indentline-config')
require('comment-config')
require('lspsaga-config')
require('yanky-config')
-- require('visual-multi-config')
require('sidebar-config')
require('dressing-config')
require('flutter-tools-config')
-- require('im-select-config')
vim.g.jupyter_ascending_python_executable = "python3"
vim.cmd('colorscheme nord')
